# Railway数据库服务配置
# 这些服务需要在Railway控制台中单独创建

[[services]]
name = "mysql-database"
type = "mysql"

[[services]]
name = "redis-cache"
type = "redis"

[[services]]
name = "influxdb-metrics"
type = "influxdb" 